// <auto-generated />
using ForgeCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForgeCore.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20260712002600_CreatingMaterialCaracteristicsRelationship")]
    partial class CreatingMaterialCaracteristicsRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForgeCore.Models.Caracteristics", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Caracteristics");
                });

            modelBuilder.Entity("ForgeCore.Models.Material", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnidadeBaseId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("ForgeCore.Models.MaterialUnidadeMedida", b =>
                {
                    b.Property<string>("Denominator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterialId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numerator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("MaterialsUnidadesMedida");
                });

            modelBuilder.Entity("ForgeCore.Models.UnidadeMedida", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("ForgeCore.Models.Caracteristics", b =>
                {
                    b.HasOne("ForgeCore.Models.Material", "Material")
                        .WithMany("Caracteristics")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("ForgeCore.Models.Material", b =>
                {
                    b.Navigation("Caracteristics");
                });
#pragma warning restore 612, 618
        }
    }
}
